version: '3'
services:
  app:
    build: .
    restart: always
    environment:
      - APP_DOMAIN=kelirskin.pegelinux.my.id
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=akumicroit
      - DB_USERNAME=root
      - DB_PASSWORD=AkuMicroIT
    depends_on:
      - db
    command: service nginx start && php-fpm
    ports:
      - 9000:80

  db:
    image: postgres:13.3
    restart: always
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: AkuMicroIT
      POSTGRES_DB: akumicroit
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: