FROM node:14 AS vite-builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

FROM composer:2 AS composer
WORKDIR /app
COPY . .  
RUN composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

FROM php:8.1-fpm
WORKDIR /var/www/html
RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    unzip \
    libpq-dev \
    && docker-php-ext-install zip pdo_pgsql \
    && docker-php-ext-enable pdo_pgsql

COPY --from=vite-builder /app/public/dist /var/www/html/public/dist
COPY --from=vite-builder /app/public/dist /var/www/html/public/build

COPY --from=composer /app/ /var/www/html/

RUN chown -R www-data:www-data /var/www/html/storage

EXPOSE 9000

CMD ["php-fpm"]